# Generated by Django 5.0.4 on 2024-04-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzone_products', '0006_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
