# Generated by Django 5.0.4 on 2024-05-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mzone_products", "0008_product_sizes_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="warranty",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
